# Generated by Django 2.1.3 on 2018-12-02 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='transcription',
        ),
        migrations.RemoveField(
            model_name='choosetranslate',
            name='translate',
        ),
        migrations.RemoveField(
            model_name='translate',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='answer',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysiteapp.Card'),
        ),
        migrations.AddField(
            model_name='choosetranslate',
            name='answer',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='mysiteapp.Answer'),
        ),
    ]
