# Generated by Django 2.1.3 on 2018-11-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='transcription',
        ),
    ]
