# Generated by Django 2.1.2 on 2018-10-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='translate',
        ),
        migrations.AddField(
            model_name='translate',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysiteapp.Card'),
        ),
    ]
