# Generated by Django 2.1.2 on 2018-11-13 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysiteapp', '0002_auto_20181028_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysiteapp.Card')),
            ],
        ),
        migrations.AlterField(
            model_name='translate',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translates', to='mysiteapp.Card'),
        ),
        migrations.AddField(
            model_name='choosetranslate',
            name='translate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='mysiteapp.Translate'),
        ),
        migrations.AddField(
            model_name='choosetranslate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='choosetranslate',
            unique_together={('card', 'user')},
        ),
    ]
