# Generated by Django 2.1.3 on 2018-11-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0002_remove_card_transcription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translate',
            name='is_correct',
        ),
    ]
