# Generated by Django 2.1.3 on 2018-12-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0003_cardword'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardword',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardword',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
