# Generated by Django 2.1.2 on 2018-11-13 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0003_auto_20181113_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choosetranslate',
            name='translate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='mysiteapp.Translate'),
        ),
    ]
