# Generated by Django 2.1.3 on 2018-12-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0004_auto_20181205_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardword',
            name='pos',
            field=models.CharField(default='', max_length=200),
        ),
    ]
